import { NextRequest, NextResponse } from 'next/server';

function reply(message: string) {
  const q = message.toLowerCase();
  if (q.includes('architecture')) return 'DustTrace fullstack flow: frontend dashboard → Next.js API routes → live air/weather APIs → AQI estimation → heatmap, forecast, reports and AI explanation.';
  if (q.includes('dataset') || q.includes('model')) return 'For ML version, collect latitude, longitude, PM2.5, PM10, temperature, humidity, wind speed, wind direction, timestamp, traffic score and area type. Train Random Forest/XGBoost to predict AQI.';
  if (q.includes('api') || q.includes('live')) return 'This version includes backend API routes. /api/aqi fetches live Open-Meteo air-quality and weather data with fallback demo data if the API is unavailable.';
  if (q.includes('heatmap')) return 'The heatmap is generated by AQI zones around Almaty. In production, backend would calculate grid points and return AQI values for every map cell.';
  if (q.includes('forecast')) return 'AQI forecast uses hourly PM2.5 data from the backend and converts it to an AQI-style risk estimate for 1 hour, 6 hours and tomorrow morning.';
  if (q.includes('route')) return 'Route intelligence compares route exposure by estimating AQI along each path and recommending the lower-exposure route, not just the shortest route.';
  return 'DustTrace is a hyperlocal AQI intelligence platform for Almaty. It connects frontend dashboards with backend AQI/weather APIs, forecast logic, heatmap visualization, reports and an AI assistant.';
}

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}));
  return NextResponse.json({ reply: reply(String(body.message || '')) });
}
